/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inilaundry;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class L1signin extends javax.swing.JFrame {

    /**
     * Creates new form signin
     */
    
    Statement stat;
    ResultSet rs;
    String sql;
    private String username, password, hashedPassword;

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    
    public L1signin() {
        initComponents();
        koneksi db = new koneksi();
        db.config();
        stat = db.stm;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        warning = new javax.swing.JLabel();
        warning1 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        masuk = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Halaman Log In - Ini Laundry");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);
        getContentPane().setLayout(null);

        warning.setFont(new java.awt.Font("Poppins", 0, 8)); // NOI18N
        warning.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(warning);
        warning.setBounds(110, 210, 280, 20);

        warning1.setFont(new java.awt.Font("Poppins", 0, 8)); // NOI18N
        warning1.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(warning1);
        warning1.setBounds(110, 150, 280, 20);

        txtusername.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        getContentPane().add(txtusername);
        txtusername.setBounds(110, 130, 280, 25);

        txtpassword.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        getContentPane().add(txtpassword);
        txtpassword.setBounds(110, 190, 280, 25);

        masuk.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        masuk.setForeground(new java.awt.Color(0, 0, 0));
        masuk.setText("Masuk");
        masuk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masukActionPerformed(evt);
            }
        });
        getContentPane().add(masuk);
        masuk.setBounds(200, 250, 100, 26);

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/whiteicon password.png"))); // NOI18N
        jLabel1.setText("Password");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 170, 140, 19);

        jLabel2.setFont(new java.awt.Font("Poppins Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Login Now");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 66, 340, 40);

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("<HTML><u>Belum Punya Akun? Daftar Sekarang</u></HTML>");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 230, 320, 16);

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/whiteicon username.png"))); // NOI18N
        jLabel4.setText("Username");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 110, 140, 19);

        jLabel5.setFont(new java.awt.Font("Poppins Black", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("INI LAUNDRY");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 7, 480, 50);

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 8)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/whiteicon 10 copyleft.png"))); // NOI18N
        jLabel6.setText("Authors");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 280, 60, 20);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/Login.png"))); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(0, 0, 500, 300);

        setSize(new java.awt.Dimension(512, 336));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // TODO add your handling code here:
        L2signup su = new L2signup();
        this.setVisible(false);
        su.setVisible(true);
    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        // TODO add your handling code here:
        L7author author = new L7author();
        author.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel6MousePressed

    private void masukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masukActionPerformed
        // TODO add your handling code here:
        try {
            L0hashing bcrypt = new L0hashing();
            this.username = txtusername.getText();
            this.password = txtpassword.getText();
        
            sql = "SELECT PASSWORD FROM user_data WHERE USERNAME = '" + this.username + "'";
            rs = stat.executeQuery(sql);
            while (rs.next()) {
                hashedPassword = rs.getString("PASSWORD");
            }
            
            boolean status = false;
            status = bcrypt.bcryptVerify(this.password, hashedPassword);
            
            if(status) {
                menu menu = new menu();
                menu.setVisible(true);
                this.setVisible(false);
            } else {
                this.warning.setText("Username / Password Salah");
                this.warning1.setText("Username / Password Salah");
            }
        } catch (Exception e) {
            this.warning1.setText("Username Tidak Terdaftar");
        }
    }//GEN-LAST:event_masukActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(L1signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(L1signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(L1signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(L1signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new L1signin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton masuk;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    private javax.swing.JLabel warning;
    private javax.swing.JLabel warning1;
    // End of variables declaration//GEN-END:variables
}
