/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inilaundry;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class L4laundry extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public L4laundry() {
        initComponents();
        this.lblhome.setVisible(false);
        this.lblhistory.setVisible(false);
        this.lbleditdata.setVisible(false);
        this.lbllogout.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolbar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        menuhome = new javax.swing.JLabel();
        lblhome = new javax.swing.JLabel();
        menulaundry = new javax.swing.JLabel();
        lbllaundry = new javax.swing.JLabel();
        menuhistory = new javax.swing.JLabel();
        lblhistory = new javax.swing.JLabel();
        menuedit = new javax.swing.JLabel();
        lbleditdata = new javax.swing.JLabel();
        menulogout = new javax.swing.JLabel();
        lbllogout = new javax.swing.JLabel();
        laundry = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ketsatuan = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        rblunas = new javax.swing.JRadioButton();
        rbbon = new javax.swing.JRadioButton();
        txtberat = new javax.swing.JTextField();
        cbcucian = new javax.swing.JComboBox<>();
        cbpaket = new javax.swing.JComboBox<>();
        satuan = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Laundry - Ini Laundry");
        setResizable(false);
        getContentPane().setLayout(null);

        toolbar.setBackground(new java.awt.Color(0, 0, 0));
        toolbar.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Poppins Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("INI LAUNDRY");

        menuhome.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        menuhome.setForeground(new java.awt.Color(255, 255, 255));
        menuhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/whiteicon home.png"))); // NOI18N
        menuhome.setText("Beranda");
        menuhome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuhomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuhomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuhomeMousePressed(evt);
            }
        });

        lblhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/grey transparan.png"))); // NOI18N

        menulaundry.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        menulaundry.setForeground(new java.awt.Color(255, 255, 255));
        menulaundry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/whiteicon wash machine.png"))); // NOI18N
        menulaundry.setText("Laundry");
        menulaundry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menulaundry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menulaundryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menulaundryMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menulaundrylaundrymenu(evt);
            }
        });

        lbllaundry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/grey transparan.png"))); // NOI18N

        menuhistory.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        menuhistory.setForeground(new java.awt.Color(255, 255, 255));
        menuhistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/whiteicon history.png"))); // NOI18N
        menuhistory.setText("Riwayat");
        menuhistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuhistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuhistoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuhistoryMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuhistoryhistorymenu(evt);
            }
        });

        lblhistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/grey transparan.png"))); // NOI18N

        menuedit.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        menuedit.setForeground(new java.awt.Color(255, 255, 255));
        menuedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/whiteicon customer.png"))); // NOI18N
        menuedit.setText("Ubah Profil");
        menuedit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menueditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menueditMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuediteditmenu(evt);
            }
        });

        lbleditdata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/grey transparan.png"))); // NOI18N

        menulogout.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        menulogout.setForeground(new java.awt.Color(255, 255, 255));
        menulogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/whiteicon logout.png"))); // NOI18N
        menulogout.setText("Keluar");
        menulogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menulogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menulogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menulogoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menulogoutMousePressed(evt);
            }
        });

        lbllogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/grey transparan.png"))); // NOI18N

        javax.swing.GroupLayout toolbarLayout = new javax.swing.GroupLayout(toolbar);
        toolbar.setLayout(toolbarLayout);
        toolbarLayout.setHorizontalGroup(
            toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(toolbarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(toolbarLayout.createSequentialGroup()
                            .addGap(230, 230, 230)
                            .addGroup(toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(menuhome, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblhome, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbllaundry, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(menulaundry, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblhistory, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(menuhistory, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(menuedit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbleditdata, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(menulogout, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbllogout, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        toolbarLayout.setVerticalGroup(
            toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(toolbarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(toolbarLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(menuhome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblhome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbllaundry, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(menulaundry, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblhistory, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(menuhistory, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(menuedit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbleditdata, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(menulogout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbllogout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(toolbar);
        toolbar.setBounds(0, 0, 800, 40);

        laundry.setBackground(new java.awt.Color(36, 36, 36));
        laundry.setForeground(new java.awt.Color(51, 51, 51));

        jLabel10.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Jenis Paket");

        jLabel11.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Jenis Cucian");

        ketsatuan.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        ketsatuan.setForeground(new java.awt.Color(255, 255, 255));
        ketsatuan.setText("Berat Cucian");

        jLabel13.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Metode Bayar");

        rblunas.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        rblunas.setForeground(new java.awt.Color(255, 255, 255));
        rblunas.setText("Lunas");
        rblunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rblunasActionPerformed(evt);
            }
        });

        rbbon.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        rbbon.setForeground(new java.awt.Color(255, 255, 255));
        rbbon.setText("Bon ( min DP 30% )");
        rbbon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbbonActionPerformed(evt);
            }
        });

        txtberat.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtberat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtberatActionPerformed(evt);
            }
        });

        cbcucian.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cbcucian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Seprai", "Selimut", "Sepatu" }));
        cbcucian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcucianActionPerformed(evt);
            }
        });

        cbpaket.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cbpaket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reguler", "Ekspress", "Kilat" }));
        cbpaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbpaketActionPerformed(evt);
            }
        });

        satuan.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        satuan.setForeground(new java.awt.Color(255, 255, 255));
        satuan.setText("kg");

        jToggleButton1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jToggleButton1.setText("Simpan");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Poppins Black", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/whiteicon wash machine.png"))); // NOI18N
        jLabel14.setText("PESAN LAUNDRY");
        jLabel14.setIconTextGap(20);

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Jumlah Bayar");

        jTextField1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout laundryLayout = new javax.swing.GroupLayout(laundry);
        laundry.setLayout(laundryLayout);
        laundryLayout.setHorizontalGroup(
            laundryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(laundryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, laundryLayout.createSequentialGroup()
                    .addGap(191, 191, 191)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(rblunas, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(rbbon, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, laundryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(laundryLayout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 318, Short.MAX_VALUE)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(laundryLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1))))
            .addGroup(laundryLayout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addGroup(laundryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(laundryLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbpaket, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(laundryLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbcucian, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(laundryLayout.createSequentialGroup()
                        .addComponent(ketsatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtberat, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(satuan))))
        );
        laundryLayout.setVerticalGroup(
            laundryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laundryLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(laundryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(laundryLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel10))
                    .addComponent(cbpaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(laundryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(laundryLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel11))
                    .addComponent(cbcucian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(laundryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtberat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(laundryLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(laundryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ketsatuan)
                            .addComponent(satuan))))
                .addGap(26, 26, 26)
                .addGroup(laundryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(laundryLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel13))
                    .addComponent(rblunas)
                    .addComponent(rbbon))
                .addGap(23, 23, 23)
                .addGroup(laundryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(laundryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(laundryLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jToggleButton1))
                    .addGroup(laundryLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );

        getContentPane().add(laundry);
        laundry.setBounds(0, 40, 800, 360);

        setSize(new java.awt.Dimension(814, 436));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuhomeMouseEntered
        // TODO add your handling code here:
        this.lblhome.setVisible(true);
    }//GEN-LAST:event_menuhomeMouseEntered

    private void menuhomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuhomeMouseExited
        // TODO add your handling code here:
        this.lblhome.setVisible(false);
    }//GEN-LAST:event_menuhomeMouseExited

    private void menuhomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuhomeMousePressed
        // TODO add your handling code here:
        L3home home = new L3home();
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuhomeMousePressed

    private void menulaundryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menulaundryMouseEntered
        // TODO add your handling code here:
        this.lbllaundry.setVisible(true);
    }//GEN-LAST:event_menulaundryMouseEntered

    private void menulaundryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menulaundryMouseExited
        // TODO add your handling code here:
        this.lbllaundry.setVisible(false);
    }//GEN-LAST:event_menulaundryMouseExited

    private void menulaundrylaundrymenu(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menulaundrylaundrymenu
        // TODO add your handling code here:
        L4laundry laundry = new L4laundry();
        laundry.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menulaundrylaundrymenu

    private void menuhistoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuhistoryMouseEntered
        // TODO add your handling code here:
        this.lblhistory.setVisible(true);
    }//GEN-LAST:event_menuhistoryMouseEntered

    private void menuhistoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuhistoryMouseExited
        // TODO add your handling code here:
        this.lblhistory.setVisible(false);
    }//GEN-LAST:event_menuhistoryMouseExited

    private void menuhistoryhistorymenu(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuhistoryhistorymenu
        // TODO add your handling code here:
        L5history history = new L5history();
        history.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuhistoryhistorymenu

    private void menueditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menueditMouseEntered
        // TODO add your handling code here:
        this.lbleditdata.setVisible(true);
    }//GEN-LAST:event_menueditMouseEntered

    private void menueditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menueditMouseExited
        // TODO add your handling code here:
        this.lbleditdata.setVisible(false);
    }//GEN-LAST:event_menueditMouseExited

    private void menuediteditmenu(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuediteditmenu
        // TODO add your handling code here:
        L6editdata edit = new L6editdata();
        edit.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuediteditmenu

    private void menulogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menulogoutMouseEntered
        // TODO add your handling code here:
        this.lbllogout.setVisible(true);
    }//GEN-LAST:event_menulogoutMouseEntered

    private void menulogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menulogoutMouseExited
        // TODO add your handling code here:
        this.lbllogout.setVisible(false);
    }//GEN-LAST:event_menulogoutMouseExited

    private void menulogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menulogoutMousePressed
        // TODO add your handling code here:
        L1signin si = new L1signin();
        si.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menulogoutMousePressed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        hitunglaundry hitung = new hitunglaundry();
        hitung.setJenisPaket(cbpaket.getSelectedItem().toString());
        hitung.setJenisCucian(cbcucian.getSelectedItem().toString());
        hitung.setJumlahCucian(Double.parseDouble(txtberat.getText()));
        hitung.setJumlahBayar(Double.parseDouble(jTextField1.getText()));
        hitung.getHargaTotal();
        JOptionPane.showMessageDialog(null, "" +hitung.getSisaBayar());
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void cbpaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbpaketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbpaketActionPerformed

    private void cbcucianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcucianActionPerformed
        // TODO add your handling code here:
        if(cbcucian.getSelectedItem().toString().equalsIgnoreCase("normal")) {
            ketsatuan.setText("Berat Cucian");
            satuan.setText("kg");
        } else{
            ketsatuan.setText("Jumlah Cucian");
            if(cbcucian.getSelectedItem().toString().equalsIgnoreCase("sepatu")){
                satuan.setText("pasang");
            } else{
                satuan.setText("buah");
            }
        }
    }//GEN-LAST:event_cbcucianActionPerformed

    private void txtberatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtberatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtberatActionPerformed

    private void rbbonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbbonActionPerformed
        // TODO add your handling code here:
        if(this.rbbon.isSelected()){
            this.rblunas.setSelected(false);
        }
    }//GEN-LAST:event_rbbonActionPerformed

    private void rblunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rblunasActionPerformed
        // TODO add your handling code here:
        if(this.rblunas.isSelected()){
            this.rbbon.setSelected(false);
        }
    }//GEN-LAST:event_rblunasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(L4laundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(L4laundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(L4laundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(L4laundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new L4laundry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbcucian;
    private javax.swing.JComboBox<String> cbpaket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel ketsatuan;
    private javax.swing.JPanel laundry;
    private javax.swing.JLabel lbleditdata;
    private javax.swing.JLabel lblhistory;
    private javax.swing.JLabel lblhome;
    private javax.swing.JLabel lbllaundry;
    private javax.swing.JLabel lbllogout;
    private javax.swing.JLabel menuedit;
    private javax.swing.JLabel menuhistory;
    private javax.swing.JLabel menuhome;
    private javax.swing.JLabel menulaundry;
    private javax.swing.JLabel menulogout;
    private javax.swing.JRadioButton rbbon;
    private javax.swing.JRadioButton rblunas;
    private javax.swing.JLabel satuan;
    private javax.swing.JPanel toolbar;
    private javax.swing.JTextField txtberat;
    // End of variables declaration//GEN-END:variables
}
