/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inilaundry;

/**
 *
 * @author HP
 */
public class L5history extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public L5history() {
        initComponents();
        this.lblhome.setVisible(false);
        this.lbllaundry.setVisible(false);
        this.lbleditdata.setVisible(false);
        this.lbllogout.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolbar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        menuhome = new javax.swing.JLabel();
        lblhome = new javax.swing.JLabel();
        menulaundry = new javax.swing.JLabel();
        lbllaundry = new javax.swing.JLabel();
        menuhistory = new javax.swing.JLabel();
        lblhistory = new javax.swing.JLabel();
        menuedit = new javax.swing.JLabel();
        lbleditdata = new javax.swing.JLabel();
        menulogout = new javax.swing.JLabel();
        lbllogout = new javax.swing.JLabel();
        history = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Riwayat - Ini Laundry");
        setResizable(false);
        getContentPane().setLayout(null);

        toolbar.setBackground(new java.awt.Color(0, 0, 0));
        toolbar.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Poppins Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("INI LAUNDRY");

        menuhome.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        menuhome.setForeground(new java.awt.Color(255, 255, 255));
        menuhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/whiteicon home.png"))); // NOI18N
        menuhome.setText("Beranda");
        menuhome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuhomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuhomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuhomeMousePressed(evt);
            }
        });

        lblhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/grey transparan.png"))); // NOI18N

        menulaundry.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        menulaundry.setForeground(new java.awt.Color(255, 255, 255));
        menulaundry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/whiteicon wash machine.png"))); // NOI18N
        menulaundry.setText("Laundry");
        menulaundry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menulaundry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menulaundryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menulaundryMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menulaundrylaundrymenu(evt);
            }
        });

        lbllaundry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/grey transparan.png"))); // NOI18N

        menuhistory.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        menuhistory.setForeground(new java.awt.Color(255, 255, 255));
        menuhistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/whiteicon history.png"))); // NOI18N
        menuhistory.setText("Riwayat");
        menuhistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuhistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuhistoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuhistoryMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuhistoryhistorymenu(evt);
            }
        });

        lblhistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/grey transparan.png"))); // NOI18N

        menuedit.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        menuedit.setForeground(new java.awt.Color(255, 255, 255));
        menuedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/whiteicon customer.png"))); // NOI18N
        menuedit.setText("Ubah Profil");
        menuedit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menueditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menueditMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuediteditmenu(evt);
            }
        });

        lbleditdata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/grey transparan.png"))); // NOI18N

        menulogout.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        menulogout.setForeground(new java.awt.Color(255, 255, 255));
        menulogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/whiteicon logout.png"))); // NOI18N
        menulogout.setText("Keluar");
        menulogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menulogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menulogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menulogoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menulogoutMousePressed(evt);
            }
        });

        lbllogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/grey transparan.png"))); // NOI18N

        javax.swing.GroupLayout toolbarLayout = new javax.swing.GroupLayout(toolbar);
        toolbar.setLayout(toolbarLayout);
        toolbarLayout.setHorizontalGroup(
            toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(toolbarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(toolbarLayout.createSequentialGroup()
                            .addGap(230, 230, 230)
                            .addGroup(toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(menuhome, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblhome, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbllaundry, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(menulaundry, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblhistory, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(menuhistory, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(menuedit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbleditdata, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(menulogout, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbllogout, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        toolbarLayout.setVerticalGroup(
            toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(toolbarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(toolbarLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(menuhome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblhome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbllaundry, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(menulaundry, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblhistory, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(menuhistory, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(menuedit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbleditdata, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(menulogout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbllogout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(toolbar);
        toolbar.setBounds(0, 0, 800, 40);

        history.setViewportView(null);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );

        history.setViewportView(jPanel4);

        getContentPane().add(history);
        history.setBounds(0, 40, 2, 2);

        setSize(new java.awt.Dimension(814, 436));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuhomeMouseEntered
        // TODO add your handling code here:
        this.lblhome.setVisible(true);
    }//GEN-LAST:event_menuhomeMouseEntered

    private void menuhomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuhomeMouseExited
        // TODO add your handling code here:
        this.lblhome.setVisible(false);
    }//GEN-LAST:event_menuhomeMouseExited

    private void menuhomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuhomeMousePressed
        // TODO add your handling code here:
        L3home home = new L3home();
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuhomeMousePressed

    private void menulaundryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menulaundryMouseEntered
        // TODO add your handling code here:
        this.lbllaundry.setVisible(true);
    }//GEN-LAST:event_menulaundryMouseEntered

    private void menulaundryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menulaundryMouseExited
        // TODO add your handling code here:
        this.lbllaundry.setVisible(false);
    }//GEN-LAST:event_menulaundryMouseExited

    private void menulaundrylaundrymenu(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menulaundrylaundrymenu
        // TODO add your handling code here:
        L4laundry laundry = new L4laundry();
        laundry.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menulaundrylaundrymenu

    private void menuhistoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuhistoryMouseEntered
        // TODO add your handling code here:
        this.lblhistory.setVisible(true);
    }//GEN-LAST:event_menuhistoryMouseEntered

    private void menuhistoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuhistoryMouseExited
        // TODO add your handling code here:
        this.lblhistory.setVisible(false);
    }//GEN-LAST:event_menuhistoryMouseExited

    private void menuhistoryhistorymenu(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuhistoryhistorymenu
        // TODO add your handling code here:
        L5history history = new L5history();
        history.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuhistoryhistorymenu

    private void menueditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menueditMouseEntered
        // TODO add your handling code here:
        this.lbleditdata.setVisible(true);
    }//GEN-LAST:event_menueditMouseEntered

    private void menueditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menueditMouseExited
        // TODO add your handling code here:
        this.lbleditdata.setVisible(false);
    }//GEN-LAST:event_menueditMouseExited

    private void menuediteditmenu(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuediteditmenu
        // TODO add your handling code here:
        L6editdata edit = new L6editdata();
        edit.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuediteditmenu

    private void menulogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menulogoutMouseEntered
        // TODO add your handling code here:
        this.lbllogout.setVisible(true);
    }//GEN-LAST:event_menulogoutMouseEntered

    private void menulogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menulogoutMouseExited
        // TODO add your handling code here:
        this.lbllogout.setVisible(false);
    }//GEN-LAST:event_menulogoutMouseExited

    private void menulogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menulogoutMousePressed
        // TODO add your handling code here:
        L1signin si = new L1signin();
        si.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menulogoutMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(L5history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(L5history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(L5history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(L5history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new L5history().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane history;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbleditdata;
    private javax.swing.JLabel lblhistory;
    private javax.swing.JLabel lblhome;
    private javax.swing.JLabel lbllaundry;
    private javax.swing.JLabel lbllogout;
    private javax.swing.JLabel menuedit;
    private javax.swing.JLabel menuhistory;
    private javax.swing.JLabel menuhome;
    private javax.swing.JLabel menulaundry;
    private javax.swing.JLabel menulogout;
    private javax.swing.JPanel toolbar;
    // End of variables declaration//GEN-END:variables
}
