/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inilaundry;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class L6editdata extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    
    Statement stat;
    ResultSet rs;
    String sql;
    L1signin si = new L1signin();
    
    public L6editdata() {
        initComponents();
        this.lblhome.setVisible(false);
        this.lbllaundry.setVisible(false);
        this.lblhistory.setVisible(false);
        this.lbllogout.setVisible(false);
    }
    
    public void updatedata (int id, String fname, String bname, String username, String phone, String domisili, String address, String postcode, String password){
        try {
            sql = "update tb_user set fname = '" +fname+ "'"
                    + ", bname = '" +bname+ "'"
                    + ", username = '" +username+ "'"
                    + ", notelp = '" +phone+ "'"
                    + ", domisili = '" +domisili+ "'"
                    + ", alamat = '" +address+ "'"
                    + ", kodepos = '" +postcode+ "'"
                    + ", password = '" +password+ "'"
                    + "where id = " +id;
            stat.executeUpdate(sql);
            
            JOptionPane.showMessageDialog(null, "Berhasil Mengubah Data");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Mengubah Data" +e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolbar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        menuhome = new javax.swing.JLabel();
        lblhome = new javax.swing.JLabel();
        menulaundry = new javax.swing.JLabel();
        lbllaundry = new javax.swing.JLabel();
        menuhistory = new javax.swing.JLabel();
        lblhistory = new javax.swing.JLabel();
        menuedit = new javax.swing.JLabel();
        lbleditdata = new javax.swing.JLabel();
        menulogout = new javax.swing.JLabel();
        lbllogout = new javax.swing.JLabel();
        edit = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtfront1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtback1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtusername1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtphone1 = new javax.swing.JTextField();
        rbsalatiga = new javax.swing.JRadioButton();
        rbluarsalatiga = new javax.swing.JRadioButton();
        txtaddress1 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtpassword1 = new javax.swing.JPasswordField();
        txtpostcode1 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        lblid = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ubah Profil - Ini Laundry");
        setResizable(false);
        getContentPane().setLayout(null);

        toolbar.setBackground(new java.awt.Color(0, 0, 0));
        toolbar.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Poppins Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("INI LAUNDRY");

        menuhome.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        menuhome.setForeground(new java.awt.Color(255, 255, 255));
        menuhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/whiteicon home.png"))); // NOI18N
        menuhome.setText("Beranda");
        menuhome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuhomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuhomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuhomeMousePressed(evt);
            }
        });

        lblhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/grey transparan.png"))); // NOI18N

        menulaundry.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        menulaundry.setForeground(new java.awt.Color(255, 255, 255));
        menulaundry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/whiteicon wash machine.png"))); // NOI18N
        menulaundry.setText("Laundry");
        menulaundry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menulaundry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menulaundryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menulaundryMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menulaundrylaundrymenu(evt);
            }
        });

        lbllaundry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/grey transparan.png"))); // NOI18N

        menuhistory.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        menuhistory.setForeground(new java.awt.Color(255, 255, 255));
        menuhistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/whiteicon history.png"))); // NOI18N
        menuhistory.setText("Riwayat");
        menuhistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuhistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuhistoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuhistoryMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuhistoryhistorymenu(evt);
            }
        });

        lblhistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/grey transparan.png"))); // NOI18N

        menuedit.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        menuedit.setForeground(new java.awt.Color(255, 255, 255));
        menuedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/whiteicon customer.png"))); // NOI18N
        menuedit.setText("Ubah Profil");
        menuedit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menueditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menueditMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuediteditmenu(evt);
            }
        });

        lbleditdata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/grey transparan.png"))); // NOI18N

        menulogout.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        menulogout.setForeground(new java.awt.Color(255, 255, 255));
        menulogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/whiteicon logout.png"))); // NOI18N
        menulogout.setText("Keluar");
        menulogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menulogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menulogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menulogoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menulogoutMousePressed(evt);
            }
        });

        lbllogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/grey transparan.png"))); // NOI18N

        javax.swing.GroupLayout toolbarLayout = new javax.swing.GroupLayout(toolbar);
        toolbar.setLayout(toolbarLayout);
        toolbarLayout.setHorizontalGroup(
            toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(toolbarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(toolbarLayout.createSequentialGroup()
                            .addGap(230, 230, 230)
                            .addGroup(toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(menuhome, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblhome, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbllaundry, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(menulaundry, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblhistory, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(menuhistory, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(menuedit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbleditdata, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(menulogout, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbllogout, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        toolbarLayout.setVerticalGroup(
            toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(toolbarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(toolbarLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(menuhome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblhome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbllaundry, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(menulaundry, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblhistory, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(menuhistory, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(menuedit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbleditdata, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(menulogout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbllogout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(toolbar);
        toolbar.setBounds(0, 0, 800, 40);

        edit.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        edit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        edit.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        jPanel6.setBackground(new java.awt.Color(36, 36, 36));
        jPanel6.setForeground(new java.awt.Color(51, 51, 51));

        jLabel24.setFont(new java.awt.Font("Poppins Black", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/whiteicon customer.png"))); // NOI18N
        jLabel24.setText("UBAH PROFIL");
        jLabel24.setIconTextGap(20);

        jLabel25.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Nama Depan");

        txtfront1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        jLabel26.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Nama Belakang");

        txtback1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        jLabel27.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Username");

        txtusername1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        jLabel28.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("No. Telp");

        jLabel29.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Domisili");

        txtphone1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        rbsalatiga.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        rbsalatiga.setForeground(new java.awt.Color(255, 255, 255));
        rbsalatiga.setText("Salatiga");
        rbsalatiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbsalatigaActionPerformed(evt);
            }
        });

        rbluarsalatiga.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        rbluarsalatiga.setForeground(new java.awt.Color(255, 255, 255));
        rbluarsalatiga.setText("Luar Salatiga");
        rbluarsalatiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbluarsalatigaActionPerformed(evt);
            }
        });

        txtaddress1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        jLabel30.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Alamat");

        jLabel31.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Kode Pos");

        jLabel32.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Password");

        txtpassword1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        txtpostcode1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        jButton6.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jButton6.setText("Simpan");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("ID");

        lblid.setForeground(new java.awt.Color(255, 255, 255));
        lblid.setText("<< ID >>");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(298, 298, 298)
                                .addComponent(jLabel24))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(235, 235, 235)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(txtusername1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(txtphone1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(rbsalatiga, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(rbluarsalatiga, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(txtaddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(txtpostcode1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(20, 20, 20)
                                            .addComponent(txtpassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(20, 20, 20)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txtback1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtfront1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(lblid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 229, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(lblid))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfront1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(txtback1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(txtusername1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(txtphone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(rbsalatiga)
                    .addComponent(rbluarsalatiga))
                .addGap(16, 16, 16)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(txtaddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(txtpostcode1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(txtpassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jButton6)
                .addGap(25, 25, 25))
        );

        edit.setViewportView(jPanel6);

        getContentPane().add(edit);
        edit.setBounds(0, 40, 800, 360);

        setSize(new java.awt.Dimension(814, 436));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuhomeMouseEntered
        // TODO add your handling code here:
        this.lblhome.setVisible(true);
    }//GEN-LAST:event_menuhomeMouseEntered

    private void menuhomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuhomeMouseExited
        // TODO add your handling code here:
        this.lblhome.setVisible(false);
    }//GEN-LAST:event_menuhomeMouseExited

    private void menuhomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuhomeMousePressed
        // TODO add your handling code here:
        L3home home = new L3home();
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuhomeMousePressed

    private void menulaundryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menulaundryMouseEntered
        // TODO add your handling code here:
        this.lbllaundry.setVisible(true);
    }//GEN-LAST:event_menulaundryMouseEntered

    private void menulaundryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menulaundryMouseExited
        // TODO add your handling code here:
        this.lbllaundry.setVisible(false);
    }//GEN-LAST:event_menulaundryMouseExited

    private void menulaundrylaundrymenu(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menulaundrylaundrymenu
        // TODO add your handling code here:
        L4laundry laundry = new L4laundry();
        laundry.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menulaundrylaundrymenu

    private void menuhistoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuhistoryMouseEntered
        // TODO add your handling code here:
        this.lblhistory.setVisible(true);
    }//GEN-LAST:event_menuhistoryMouseEntered

    private void menuhistoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuhistoryMouseExited
        // TODO add your handling code here:
        this.lblhistory.setVisible(false);
    }//GEN-LAST:event_menuhistoryMouseExited

    private void menuhistoryhistorymenu(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuhistoryhistorymenu
        // TODO add your handling code here:
        L5history history = new L5history();
        history.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuhistoryhistorymenu

    private void menueditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menueditMouseEntered
        // TODO add your handling code here:
        this.lbleditdata.setVisible(true);
    }//GEN-LAST:event_menueditMouseEntered

    private void menueditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menueditMouseExited
        // TODO add your handling code here:
        this.lbleditdata.setVisible(false);
    }//GEN-LAST:event_menueditMouseExited

    private void menuediteditmenu(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuediteditmenu
        // TODO add your handling code here:
        L6editdata edit = new L6editdata();
        edit.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuediteditmenu

    private void menulogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menulogoutMouseEntered
        // TODO add your handling code here:
        this.lbllogout.setVisible(true);
    }//GEN-LAST:event_menulogoutMouseEntered

    private void menulogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menulogoutMouseExited
        // TODO add your handling code here:
        this.lbllogout.setVisible(false);
    }//GEN-LAST:event_menulogoutMouseExited

    private void menulogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menulogoutMousePressed
        // TODO add your handling code here:
        L1signin si = new L1signin();
        si.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menulogoutMousePressed

    private void rbsalatigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbsalatigaActionPerformed
        // TODO add your handling code here:
        if(this.rbsalatiga.isSelected())
        this.rbluarsalatiga.setSelected(false);
    }//GEN-LAST:event_rbsalatigaActionPerformed

    private void rbluarsalatigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbluarsalatigaActionPerformed
        // TODO add your handling code here:
        if(this.rbluarsalatiga.isSelected())
        this.rbsalatiga.setSelected(false);
    }//GEN-LAST:event_rbluarsalatigaActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(L6editdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(L6editdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(L6editdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(L6editdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new L6editdata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane edit;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbleditdata;
    private javax.swing.JLabel lblhistory;
    private javax.swing.JLabel lblhome;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lbllaundry;
    private javax.swing.JLabel lbllogout;
    private javax.swing.JLabel menuedit;
    private javax.swing.JLabel menuhistory;
    private javax.swing.JLabel menuhome;
    private javax.swing.JLabel menulaundry;
    private javax.swing.JLabel menulogout;
    private javax.swing.JRadioButton rbluarsalatiga;
    private javax.swing.JRadioButton rbsalatiga;
    private javax.swing.JPanel toolbar;
    private javax.swing.JTextField txtaddress1;
    private javax.swing.JTextField txtback1;
    private javax.swing.JTextField txtfront1;
    private javax.swing.JPasswordField txtpassword1;
    private javax.swing.JTextField txtphone1;
    private javax.swing.JTextField txtpostcode1;
    private javax.swing.JTextField txtusername1;
    // End of variables declaration//GEN-END:variables
}
