/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inilaundry;

/**
 *
 * @author HP
 */
public class L7author extends javax.swing.JFrame {

    /**
     * Creates new form author
     */
    public L7author() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Poppins Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html>\n<center><p>Anthony Febrian</p><br></center>\n<center><p>672021037</p></center>\n</html>");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(440, 320, 150, 80);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/author ello 150x270.jpeg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(240, 50, 150, 270);

        jLabel6.setFont(new java.awt.Font("Poppins Black", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("<html>\n<center><p>Gabriel Mika Angelo</p><br></center>\n<center><p>6720210012</p></center>\n</html>");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(240, 320, 150, 80);

        jLabel7.setFont(new java.awt.Font("Poppins Black", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("<html>\n<center><p>Kevin Nathanael</p><br></center>\n<center><p>672021005</p></center>\n</html>");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 320, 150, 80);

        jLabel8.setFont(new java.awt.Font("Poppins Black", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("<html>\n<center><p>Leonnyndra Putra</p><br></center>\n<center><p>672021152</p></center>\n</html>");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(630, 320, 150, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/author kevin 150x270.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 50, 150, 270);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/author leon 150x270.jpeg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(630, 50, 150, 270);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/icons8-back-48.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 0, 48, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/author anthony 150x270.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(440, 50, 150, 270);

        jLabel4.setFont(new java.awt.Font("Poppins Black", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("AUTHORS");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -3, 800, 50);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inilaundry/tot/App.png"))); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(0, 0, 800, 400);

        setSize(new java.awt.Dimension(814, 436));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        // TODO add your handling code here:
        L1signin si = new L1signin();
        si.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel10MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(L7author.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(L7author.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(L7author.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(L7author.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new L7author().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
